import datetime

from app.domain.entities.entities import Operation, OperationType, Reference, Ticket
from app.domain.entities.enums import HBTypeOperations

mock_operations = [
    # Buy operations (total: 4)
    Operation(
        id=1,
        type_operation=OperationType(type_operation=HBTypeOperations.BUY),
        ticket=Ticket(species="AAPL", species_code="AAPL", ticker="AAPL"),
        code="BUY001",
        accumulated=100.0,
        number_receipt=1001,
        date_liquidation=datetime.date(2024, 1, 15),
        date_operation=datetime.date(2024, 1, 15),
        reference=Reference(detail="Buy AAPL shares"),
        import_of_operation=100.0,
        comprobant_of_operation=1001,
        amount=100.0,
        price_of_operation=1.0,
    ),
    Operation(
        id=2,
        type_operation=OperationType(type_operation=HBTypeOperations.BUY),
        ticket=Ticket(species="AAPL", species_code="AAPL", ticker="AAPL"),
        code="BUY002",
        accumulated=200.0,
        number_receipt=1002,
        date_liquidation=datetime.date(2024, 1, 20),
        date_operation=datetime.date(2024, 1, 20),
        reference=Reference(detail="Buy more AAPL shares"),
        import_of_operation=200.0,
        comprobant_of_operation=1002,
        amount=100.0,
        price_of_operation=2.0,
    ),
    Operation(
        id=3,
        type_operation=OperationType(type_operation=HBTypeOperations.BUY),
        ticket=Ticket(species="MSFT", species_code="MSFT", ticker="MSFT"),
        code="BUY003",
        accumulated=50.0,
        number_receipt=1003,
        date_liquidation=datetime.date(2024, 2, 1),
        date_operation=datetime.date(2024, 2, 1),
        reference=Reference(detail="Buy MSFT shares"),
        import_of_operation=50.0,
        comprobant_of_operation=1003,
        amount=50.0,
        price_of_operation=1.0,
    ),
    Operation(
        id=4,
        type_operation=OperationType(type_operation=HBTypeOperations.BUY),
        ticket=Ticket(species="AAPL", species_code="AAPL", ticker="AAPL"),
        code="BUY004",
        accumulated=300.0,
        number_receipt=1004,
        date_liquidation=datetime.date(2024, 2, 10),
        date_operation=datetime.date(2024, 2, 10),
        reference=Reference(detail="Buy additional AAPL shares"),
        import_of_operation=300.0,
        comprobant_of_operation=1004,
        amount=100.0,
        price_of_operation=3.0,
    ),
    # Sell operations (total: 3)
    Operation(
        id=5,
        type_operation=OperationType(type_operation=HBTypeOperations.SELL),
        ticket=Ticket(species="AAPL", species_code="AAPL", ticker="AAPL"),
        code="SELL001",
        accumulated=200.0,
        number_receipt=2001,
        date_liquidation=datetime.date(2024, 2, 15),
        date_operation=datetime.date(2024, 2, 15),
        reference=Reference(detail="Sell AAPL shares"),
        import_of_operation=200.0,
        comprobant_of_operation=2001,
        amount=100.0,
        price_of_operation=2.0,
    ),
    Operation(
        id=6,
        type_operation=OperationType(type_operation=HBTypeOperations.SELL),
        ticket=Ticket(species="AAPL", species_code="AAPL", ticker="AAPL"),
        code="SELL002",
        accumulated=100.0,
        number_receipt=2002,
        date_liquidation=datetime.date(2024, 2, 20),
        date_operation=datetime.date(2024, 2, 20),
        reference=Reference(detail="Sell more AAPL shares"),
        import_of_operation=100.0,
        comprobant_of_operation=2002,
        amount=100.0,
        price_of_operation=1.0,
    ),
    Operation(
        id=7,
        type_operation=OperationType(type_operation=HBTypeOperations.SELL),
        ticket=Ticket(species="MSFT", species_code="MSFT", ticker="MSFT"),
        code="SELL003",
        accumulated=0.0,
        number_receipt=2003,
        date_liquidation=datetime.date(2024, 2, 25),
        date_operation=datetime.date(2024, 2, 25),
        reference=Reference(detail="Sell MSFT shares"),
        import_of_operation=50.0,
        comprobant_of_operation=2003,
        amount=50.0,
        price_of_operation=1.0,
    ),
    # Other operations (total: 3)
    Operation(
        id=8,
        type_operation=OperationType(type_operation=HBTypeOperations.DIVIDEND),
        ticket=Ticket(species="AAPL", species_code="AAPL", ticker="AAPL"),
        code="DIV001",
        accumulated=0.0,
        number_receipt=3001,
        date_liquidation=datetime.date(2024, 3, 1),
        date_operation=datetime.date(2024, 3, 1),
        reference=Reference(detail="AAPL dividend payment"),
        import_of_operation=10.0,
        comprobant_of_operation=3001,
        amount=0.0,
        price_of_operation=None,
    ),
    Operation(
        id=9,
        type_operation=OperationType(type_operation=HBTypeOperations.RECEIPT),
        ticket=Ticket(species="CASH", species_code="CASH", ticker="CASH"),
        code="REC001",
        accumulated=0.0,
        number_receipt=3002,
        date_liquidation=datetime.date(2024, 3, 5),
        date_operation=datetime.date(2024, 3, 5),
        reference=Reference(detail="Cash receipt"),
        import_of_operation=1000.0,
        comprobant_of_operation=3002,
        amount=0.0,
        price_of_operation=None,
    ),
    Operation(
        id=10,
        type_operation=OperationType(type_operation=HBTypeOperations.PAYMENT_ORDER),
        ticket=Ticket(species="CASH", species_code="CASH", ticker="CASH"),
        code="PAY001",
        accumulated=0.0,
        number_receipt=3003,
        date_liquidation=datetime.date(2024, 3, 10),
        date_operation=datetime.date(2024, 3, 10),
        reference=Reference(detail="Payment order"),
        import_of_operation=-500.0,
        comprobant_of_operation=3003,
        amount=0.0,
        price_of_operation=None,
    ),
]
